#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Make sure that HAproxy can be managed via an init script

# Update package list and install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup existing HAproxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAproxy to distribute traffic to web-01 and web-02 using a round-robin algorithm
echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend

backend lb-backend
        balance roundrobin
        server web-01 54.209.211.244:80 check
        server web-02 54.196.244.48:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Ensure HAproxy is managed via an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAproxy to apply changes
sudo service haproxy restart

# Enable HAproxy to start on boot
sudo systemctl enable haproxy

# Output message showing the configured servers
echo 'Configured HAproxy with servers: ["web-01", "web-02"]'

